[build]

  functions = "functions"
  publish = "public"
  command = "gatsby build"

 [dev]
    command = "yarn start"
    port = 8000

[headers]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
