# example netlify.toml
[build]
  base = "site"
  command = "gatsby build"
  functions = "functions"
  publish = "public"  
    
 [dev] 
    command = "yarn start" 
    port = 8000 
    publish = "public" 
  
  
